name: secret test

on:
  workflow_call:
    secrets:
      TEST_POP:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run secret_test workflow
        uses: ./.github/workflows/secret_test.yml
        with:
          secrets:
            TEST_POP: ${{ secrets.POP }}