name: secret test

on:
  workflow_call:
    secrets:
      TEST_POP:
        required: true

env:
  TEST_POP: ${{ secrets.TEST_POP }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jksdhfjkahd
        run: |
          echo ${{ secrets.TEST_POP}}
          echo -n $TEST_POP
          echo -n $TEST_POP | wc -m
