name: secret test

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - env:
          TEST_POP: ${{secrets.POP}}
        run: |
          echo $TEST_POP | wc -m
