name: main test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run secret_test workflow
        uses: ./.github/workflows/secret_test.yml
        with:
          secrets:
            TEST_POP: ${{ secrets.POP }}