name: main test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run secret_test workflow
        uses: ./.github/workflows/secret_test.yml
        env:
          TEST_POP: ${{ secrets.POP }}